import Button from '@/app/components/Button';
import Image from 'next/image';
import React from 'react';
import img from '@/public/images/abc.jpg'

export const metadata = {
    title: 'Mission',
    description: 'Generated by create next app',
  }

export default function page() {
    
    return (
        <main>
            <h1 className="">Reference site about Lorem Ipsum, giving information on its origins, as well as a random Lipsum generator.</h1>
            
            <Image 
            src={img} 
            alt='' 
            width={400}
            placeholder='blur'
            />
            
            <Button/>
        </main>
    );
}